public enum Menu
{
    MAIN_MENU,
    WEIGHT_MENU,
    MEASURE_MENU,
    AGE_MENU,
    MEDICATION_MENU,
    BARCODE_MENU,
    UNABLE_TO_SCAN_MENU,
    DRAW_MEDICATION_MENU,
    ADMINISTER_MENU,
    BLOOD_SUGAR_LEVEL_MENU,
    FINAL_MENU
}
